services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "LOCAL://:9092,DOCKER://:9094,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "LOCAL://localhost:9092,DOCKER://kafka:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "LOCAL:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "DOCKER"
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose -f "docker-compose-kafka.yml" -p micro-kafka up -d

#> docker exec kafka kafka-topics.sh --list --bootstrap-server localhost:9092

#> docker exec -it --user root kafka bash