services:
  app:
    build: .
    image: order-api:v1
    container_name: order-api
    restart: always
    ports:
      - "8082:8082"
    environment:
      MIW_URL_USER-API: http://host.docker.internal:8081
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9094
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose -p pro-kafka up --build -d