services:
  order-api-server:
    build: .
    image: order-api:1.1.0
    container_name: order-api-server
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9094
      MIW_URL_MICRO-USER-API: http://host.docker.internal:8081
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose up --build -d