services:
  order-api-server:
    build: .
    image: order-api:v1
    container_name: order-api-server
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9094
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose up --build -d