name: CI
on:
  push:
    branches: [develop]

jobs:
  devops:
    name: Test - Unit & Integration & SonarCloud Scan
    runs-on: ubuntu-22.04
    services:
      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        env:
          ALLOW_PLAINTEXT_LISTENER: "yes"
          KAFKA_CFG_NODE_ID: 1
          KAFKA_CFG_PROCESS_ROLES: broker,controller
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: 'yes'


    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: maven

      - name: Build & Unit & IT & FT & Sonar Analysis
        run: >
          mvn -B clean verify sonar:sonar 
          -Dsonar.projectKey=es.upm.miw:iwvg-devops 
          -Dsonar.organization=miw-upm-github 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
